e-commerce-master/DotNetShopping/Controllers/ProductController.cs
using DotNetShopping.Helpers;
using DotNetShopping.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetShopping.Controllers
{
    public class ProductController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        

        public ActionResult Index()
        {
            var products = db.Products.Include("Brands").Include("Suppliers")
                .Join(db.Variants, p => p.ProductId, v => v.ProductId, (p, v) => new { Product = p, Variant = v })
                .Join(db.Categories, pv => pv.Product.CategoryId, c => c.CategoryId, (pv, c) => new { pv, Category = c })
                .Where(x => x.pv.Product.Archived == false && x.pv.Variant.Archived == false)
                .OrderByDescending(x => x.pv.Product.ProductId)
                .Select(x => new ProductListModel
                {
                    ProductId = x.pv.Product.ProductId,
                    VariantId = x.pv.Variant.VariantId,
                    ProductName = x.pv.Product.Name,
                    VariantName = x.pv.Variant.Name,
                    BrandName = x.pv.Product.Brand.Name,
                    SupplierName = x.pv.Product.Supplier.Name,
                    CategoryName = x.Category.Name,
                    Cost = x.pv.Variant.Cost,
                    IsVisible = x.pv.Product.IsVisible == true ? x.pv.Variant.IsVisible : false,
                    OnSale = x.pv.Product.OnSale,
                    Stock = x.pv.Variant.Stock,
                    UnitPrice = x.pv.Variant.UnitPrice,
                    PhotoName = db.ProductImages.Where(i => i.VariantId == x.pv.Variant.VariantId).OrderBy(i => i.Sequence).FirstOrDefault().FileName
                });
            return View(products.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.SupplierId = new SelectList(db.Suppliers.OrderBy(x => x.Name), "SupplierId", "Name");
            ViewBag.BrandId = new SelectList(db.Brands.OrderBy(x => x.Name), "BrandId", "Name");
            ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.Name), "CategoryId", "Name");
            ViewBag.CampaignId = new SelectList(db.Campaigns.Where(x => x.ProductCampaign == true).OrderBy(x => x.Name), "CampaignId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductCreateModel model)
        {
            ViewBag.Error = "";
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.UploadedFile != null)
                    {
                        var image = System.Drawing.Image.FromStream(model.UploadedFile.InputStream);
                        if (image.Width >= 1000 && image.Height >= 1000)
                        {
                            var today = DateTime.Today;
                            var p = new Product();
                            p.Name = model.ProductName;
                            p.BrandId = model.BrandId;
                            p.Archived = false;
                            p.CategoryId = model.CategoryId;
                            p.CreateDate = today;
                            p.CreateUser = User.Identity.GetUserId();
                            p.UpdateDate = today;
                            p.UpdateUser = User.Identity.GetUserId();
                            p.Unit = model.Unit;
                            p.SupplierId = model.SupplierId;
                            p.OnSale = model.OnSale;
                            p.IsVisible = model.IsVisible;
                            p.Description = model.Description;
                            p.CampaignId = model.CampaignId ?? 0;
                            db.Products.Add(p);
                            db.SaveChanges();

                            var v = new Variant();
                            v.ProductId = p.ProductId;
                            v.Archived = false;
                            v.Cost = model.Cost;
                            v.CreateDate = today;
                            v.CreateUser = User.Identity.GetUserId();
                            v.UpdateDate = today;
                            v.UpdateUser = User.Identity.GetUserId();
                            v.IsVisible = model.IsVisible;
                            v.Name = model.VariantName;
                            v.Stock = model.Stock;
                            v.UnitPrice = model.UnitPrice;
                            db.Variants.Add(v);
                            db.SaveChanges();


                            var productImage = new ProductImage();
                            string fileName = productImage.InsertProductImage(v.VariantId);
                            ImageHelper.SaveImage(fileName, image);

                            return RedirectToAction("Index");
                        }
                        else
                        {
                            throw new Exception("Photo needs to be minimum 1000px X 1000px size!");
                        }
                    }
                }
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.SupplierId = new SelectList(db.Suppliers.OrderBy(x => x.Name), "SupplierId", "Name", model.SupplierId);
            ViewBag.BrandId = new SelectList(db.Brands.OrderBy(x => x.Name), "BrandId", "Name", model.BrandId);
            ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.Name), "CategoryId", "Name", model.CategoryId);
            ViewBag.CampaignId = new SelectList(db.Campaigns.Where(x => x.ProductCampaign == true).OrderBy(x => x.Name), "CampaignId", "Name", model.CampaignId);
            return View();
        }

        public ActionResult Edit(Int64 id)
        {
            var product = db.Products.Find(id);
            if (product != null)
            {
                var model = new ProductEditModel
                {
                    ProductId = product.ProductId,
                    ProductName = product.Name,
                    BrandId = product.BrandId,
                    SupplierId = product.SupplierId,
                    CategoryId = product.CategoryId,
                    Description = product.Description,
                    IsVisible = product.IsVisible,
                    OnSale = product.OnSale,
                    Unit = product.Unit,
                    CampaignId = product.CampaignId
                };
                ViewBag.SupplierId = new SelectList(db.Suppliers.OrderBy(x => x.Name), "SupplierId", "Name", model.SupplierId);
                ViewBag.BrandId = new SelectList(db.Brands.OrderBy(x => x.Name), "BrandId", "Name", model.BrandId);
                ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.Name), "CategoryId", "Name", model.CategoryId);
                ViewBag.CampaignId = new SelectList(db.Campaigns.Where(x => x.ProductCampaign == true).OrderBy(x => x.Name), "CampaignId", "Name", model.CampaignId);
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", new { Error = "Product Not Found" });
            }
        }

        [HttpPost]
        public ActionResult Edit(ProductEditModel model)
        {
            var product = db.Products.Find(model.ProductId);
            if (product != null)
            {
                product.Name = model.ProductName;
                product.BrandId = model.BrandId;
                product.CategoryId = model.CategoryId;
                product.Description = model.Description;
                product.IsVisible = model.IsVisible;
                product.OnSale = model.OnSale;
                product.SupplierId = model.SupplierId;
                product.Unit = model.Unit;
                product.UpdateDate = DateTime.Today;
                product.UpdateUser = User.Identity.GetUserId();
                product.CampaignId = model.CampaignId ?? 0;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.SupplierId = new SelectList(db.Suppliers.OrderBy(x => x.Name), "SupplierId", "Name", model.SupplierId);
                ViewBag.BrandId = new SelectList(db.Brands.OrderBy(x => x.Name), "BrandId", "Name", model.BrandId);
                ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.Name), "CategoryId", "Name", model.CategoryId);
                ViewBag.CampaignId = new SelectList(db.Campaigns.Where(x => x.ProductCampaign == true).OrderBy(x => x.Name), "CampaignId", "Name", model.CampaignId);
                return View(model);
            }
        }

        public ActionResult Delete(Int64 id)
        {
            var product = db.Products.Find(id);
            product.Archived = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Variants(Int64 id = 0)
        {
            if (id == 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var model = db.Variants.Where(x => x.ProductId == id && !x.Archived)
                    .Select(x => new VariantListModel
                    {
                        VariantId = x.VariantId,
                        VariantName = x.Name,
                        Cost = x.Cost,
                        IsVisible = x.IsVisible,
                        ProductId = x.ProductId,
                        Stock = x.Stock,
                        UnitPrice = x.UnitPrice,
                        PhotoName = db.ProductImages.Where(i => i.VariantId == x.VariantId).OrderBy(i => i.Sequence).FirstOrDefault().FileName
                    });

e-commerce-master/DotNetShopping/Controllers/ProductDetailController.cs
using DotNetShopping.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetShopping.Controllers
{
    public class ProductDetailController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: ProductDetail
        public ActionResult Product(Int64 id, string name)
        {
            var model = db.Variants.Include("Product").Include("Brand")
                .Where(x => x.VariantId == id && x.Archived == false && x.Product.Archived == false
                && x.IsVisible == true)
                .Join(db.Categories, v => v.Product.CategoryId,
                c => c.CategoryId, (v, c) => new { Variant = v, Category = c })
                .Select(x => new ProductDetailModel
                {
                    ProductId = x.Variant.ProductId,
                    VariantId = x.Variant.VariantId,
                    ProductName = x.Variant.Product.Name,
                    VariantName = x.Variant.Name,
                    BrandName = x.Variant.Product.Brand.Name,
                    CategoryName = x.Category.Name,
                    UnitPrice = x.Variant.UnitPrice,
                    BrandId = x.Variant.Product.BrandId,
                    CategoryId = x.Variant.Product.CategoryId,
                    Description = x.Variant.Product.Description,
                    OnSale = x.Variant.Product.OnSale,
                    Stock = x.Variant.Stock,
                    Unit = x.Variant.Product.Unit,
                    Images = db.ProductImages
                    .Where(i => i.VariantId == x.Variant.VariantId)
                    .OrderBy(i => i.Sequence).ToList(),
                    CampaignName = x.Variant.Product.CampaignId == 0 ? "" :
                    db.Campaigns.Where(c => c.CampaignId == x.Variant.Product.CampaignId).FirstOrDefault().Name
                }).FirstOrDefault();
            if (model == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var otherVariants = db.Variants
                .Where(x => x.Archived == false && x.Product.Archived == false
                && x.IsVisible == true && x.Stock > 0 && x.Product.OnSale == true 
                && x.ProductId == model.ProductId && x.VariantId != id)
                .Select(x => new ProductBoxModel
                {
                    ProductId = x.ProductId,
                    VariantId = x.VariantId,
                    VariantName = x.Name,
                    UnitPrice = x.UnitPrice,
                    PhotoName = db.ProductImages
                    .Where(i => i.VariantId == x.VariantId)
                    .OrderBy(i => i.Sequence).FirstOrDefault().FileName
                })
                .ToList();
            ViewBag.OtherVariants = otherVariants;

            return View(model);
        }

        
    }
}

e-commerce-master/DotNetShopping/Views/ProductDetail/Product.cshtml
@model DotNetShopping.Models.ProductDetailModel
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <hr />
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="slider-for">
                @foreach (DotNetShopping.Models.ProductImage pi in Model.Images)
                {
                    <img src="~/ProductImage/@(pi.FileName)-6.jpg" />
                }
            </div>
            <div class="slider-nav">
                @foreach (DotNetShopping.Models.ProductImage pi in Model.Images)
                {
                    <img src="~/ProductImage/@(pi.FileName)-2.jpg" />
                }
            </div>
        </div>
        <div class="col-md-8">
            <div><h1>@Model.VariantName - @Model.ProductName</h1></div>
            <div><p>@Model.Description</p></div>
            <div><p>Availability : @(Model.Stock > 0 ? "In Stock" : "Out of Stock")</p></div>
            <div class="price"><i class="glyphicon glyphicon-tag"></i><p>$@(Model.UnitPrice)</p></div>
            @if (Model.CampaignName != "")
            {
                <div class="productdetail-label"><span class="sale-product-icon">@Model.CampaignName</span></div>
            }
            @{
                List<DotNetShopping.Models.ProductBoxModel> otherVariants = ViewBag.OtherVariants;
                if (otherVariants.Count > 0)
                {
                    <div class="OtherVariants">
                        <div class="Item Selected">
                            <img src="~/ProductImage/@(Model.Images.First().FileName)-1.jpg" />
                            <div>@Model.VariantName</div>
                        </div>
                        @foreach (DotNetShopping.Models.ProductBoxModel item in otherVariants)
                        {
                            <a href="@Url.Action("Product", "ProductDetail", new { id = item.VariantId, name = DotNetShopping.Helpers.StringHelper.ClearFileName(item.VariantName + " " + Model.ProductName) })">
                                <div class="Item">
                                    <img src="~/ProductImage/@(item.PhotoName)-1.jpg" />
                                    <div>@item.VariantName</div>
                                </div>
                            </a>
                        }
                    </div>
                }
            }
            <div class="add-to-box">
                <div class="add-to-cart">
                    <label for="qty">Qty:</label>
                    <div class="qty-holder">
                        <input type="text" name="qty" id="qty" maxlength="12" value="1" title="Qty" class="input-text qty">
                        <div class="qty-changer">
                            <a href="javascript:plusClick();" class="qty_inc"><i class="glyphicon glyphicon-plus"></i></a>
                            <a href="javascript:minusClick();" class="qty_dec"><i class="glyphicon glyphicon-minus"></i></a>
                        </div>
                    </div>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <button type="button" title="Add to Cart" class="button btn-cart" onclick="addToCart(@Model.VariantId, parseInt($('#qty').val()));"><span><span>Add to Cart</span></span></button>
                    }
                    else
                    {
                        <button type="button" title="Add to Cart" class="button btn-cart" onclick="window.location = '@Url.Action("Login", "Account", new { returnUrl = Url.Action("Product", "ProductDetail", new { id = Model.VariantId, name = DotNetShopping.Helpers.StringHelper.ClearFileName(Model.VariantName + " " + Model.ProductName) }) })';"><span><span>Add to Cart</span></span></button>
                    }

                </div>
                <ul class="add-to-links">
                    <li><a href="#" onclick="" class="link-wishlist"><i class="glyphicon glyphicon-heart"></i><span>Add to Wishlist</span></a></li>
                    <li><a href="#" onclick="" class="link-compare"><i class="glyphicon glyphicon-signal"></i><span>Add to Compare</span></a></li>

                </ul>
            </div>
        </div>
    </div>
</div>
@section head {
    <link href="~/Content/Site/slick.css" rel="stylesheet" />
    <link href="~/Content/Site/slick-theme.css" rel="stylesheet" />
}
@section scripts {
    <script src="~/Scripts/slick.min.js"></script>
    <script type="text/javascript">
        function minusClick() {
            var qty = parseInt($('#qty').val());
            if (qty > 1) {
                qty--;
                $('#qty').val(qty);
            }
        }
        function plusClick() {
            var qty = parseInt($('#qty').val());
            if (qty < @Model.Stock) {
                qty++;
                $('#qty').val(qty);
            }
        }
    </script>
}
@section scriptsready {
    $('.slider-for').slick({
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: false,
    fade: true,
    asNavFor: '.slider-nav'
    });
    $('.slider-nav').slick({
    slidesToShow: 3,
    slidesToScroll: 1,
    asNavFor: '.slider-for',
    dots: true,
    centerMode: true,
    focusOnSelect: true
    });

}